[package]
name = "morsdb"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ["txn", "sync"]
sync = []
txn = []
[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
mors-common = { workspace = true }
mors-traits = { workspace = true }
mors-encrypt = { workspace = true }
mors-levelctl = { workspace = true }
mors-memtable = { workspace = true }
mors-skip_list = { workspace = true }
mors-sstable = { workspace = true }
mors-wal = { workspace = true }
mors-vlog = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
# tokio-util = { workspace = true, features = ["full"] }
lazy_static = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
ahash = { workspace = true }
rand = { workspace = true }
env_logger = { workspace = true }
[dev-dependencies]
console-subscriber = { workspace = true }

[target.'cfg(not(target_os = "wasi"))'.dev-dependencies]
# Pinned to compatibility with MSRV
ctrlc = "=3.4.5"
heed = "0.20"
sanakirja = "=1.4.3"
sanakirja-core = "=1.4.1"
rocksdb = "0.22.0"
comfy-table = "7.0.1"
redb = "2.1.4"
sled = "0.34.7"
tempfile = "3.2.0"
walkdir = "2.5.0"
byte-unit = "=5.0.4"
fastrand = "2.0.0"
[[example]]
name = "simple"
path = "examples/simple.rs"

[[bench]]
name = "benchmark"
harness = false
