// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Checksum {
    /// For storing type of Checksum algorithm used
    #[prost(enumeration = "checksum::Algorithm", tag = "1")]
    pub algo: i32,
    #[prost(uint64, tag = "2")]
    pub sum: u64,
}
/// Nested message and enum types in `Checksum`.
pub mod checksum {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Algorithm {
        Crc32c = 0,
        XxHash64 = 1,
    }
    impl Algorithm {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Algorithm::Crc32c => "CRC32C",
                Algorithm::XxHash64 => "XXHash64",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CRC32C" => Some(Self::Crc32c),
                "XXHash64" => Some(Self::XxHash64),
                _ => None,
            }
        }
    }
}
